"""add_portfolios_table

Revision ID: 37ddb5ac73b4
Revises: 4f8a2a15eb5a
Create Date: 2024-04-19 16:06:46.523200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '37ddb5ac73b4'
down_revision: Union[str, None] = '4f8a2a15eb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portfolios',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('portfolio_shares_id', sa.BigInteger(), nullable=True),
        sa.Column('portfolio_options_id', sa.BigInteger(), nullable=True),
        sa.Column('cash', sa.Numeric(precision=18, scale=2), server_default='0.00', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    # ### end Alembic commands ###
