"""add_portfolio_shares_table

Revision ID: 9fd14083020b
Revises: 37ddb5ac73b4
Create Date: 2024-04-19 16:09:27.962135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9fd14083020b'
down_revision: Union[str, None] = '37ddb5ac73b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portfolio_shares',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
        sa.Column('ticker_share_type_id', sa.BigInteger(), nullable=False),
        sa.Column('count', sa.Numeric(precision=24, scale=10), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['ticker_share_type_id'], ['ticker_share_types.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_shares')
    # ### end Alembic commands ###
